### ISSUE TITLE
Adding a breakpoint doesn't work

### ISSUE THREAD

**Issue by gdonald** [jnthn/rakudo-debugger#49]
```
> bp add Validators:55
Cannot add breakpoint to unknown file 'Validators'
> bp add Validators.pm6:55
Cannot add breakpoint to unknown file 'Validators.pm6'
```

¯\\_(ツ)_/¯

**Comment by jnthn** [comment]
I suggest trying the newer VM-level debugger, for which both [GUI](https://commaide.com/) and [command line](https://github.com/edumentab/p6-app-moarvm-debug) clients exist.

**Comment by gdonald** [comment]
Will do, thanks.  Closing.

**Comment by jnthn** [comment]
I've also updated the `README` to directly folks to the newer thing. Sorry for neglecting to do that before now.
